#ifndef PINS_H
#define PINS_H

//Timer Pins
#define TIMER0_CNTR TCNT0
#define TIMER0_CTR_REG_A TCCR0A
#define TIMER0_CTR_REG_B TCCR0B 
#define TIMER0_INT_MASK TIMSK0
#define TIMER0_INT_FLAG_REG TIFR0

#define TIMER1_CNTR TCNT1
#define TIMER1_CNTR_H TCNT1H
#define TIMER1_CNTR_L TCNT1L
#define TIMER1_CTR_REG_A TCCR1A
#define TIMER1_CTR_REG_B TCCR1B 
#define TIMER1_INT_MASK TIMSK1
#define TIMER1_INT_FLAG_REG TIFR1

//UART Pins
#define UART_CTR_STATUS_REG0_A UCSR0A
#define UART_CTR_STATUS_REG0_B UCSR0B
#define UART_CTR_STATUS_REG0_C UCSR0C
#define UART_BAUD_RATE_REG0_H UBRR0H
#define UART_BAUD_RATE_REG0_L UBRR0L

//PWM Pins
#define PWM0 PD3

//Ultrasonic Sensor Pins
//TO BE UPDATED
#define US1_ECHO PB0
#define US1_TRIG PB4

#define US2_ECHO PD2
#define US2_TRIG PB3

//Servo Motor Pins
#define SERVO1_CTRL PB2

#endif